services:
  gnn_tcc_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.gpu
      network: host # Bypass de DNS do WSL2
    container_name: gnn_tcc_container_gpu
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ..:/app/gnn_tcc
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
    ulimits:
      memlock: -1
      stack: 67108864
    working_dir: /app/gnn_tcc
    command: ["/bin/bash", "-c", "while true; do sleep infinity; done"]